# app/models/models.py
#
# PURPOSE: Define your database schema as Python classes.
#
# YOUR OLD FLASK APPROACH:
#   Raw SQL strings scattered across init_db():
#   c.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, ...)")
#   Different syntax for SQLite vs Postgres (?  vs %s)
#
# THE SQLALCHEMY ORM APPROACH:
#   Define tables as Python classes. SQLAlchemy handles:
#   - Table creation for both SQLite and Postgres
#   - The ? vs %s difference (uses its own parameter binding)
#   - Type checking and conversion
#   - Relationships between tables
#
# HOW IT WORKS:
#   class User(Base):             ← Python class
#       __tablename__ = "users"   ← maps to SQL table "users"
#       id = Column(Integer, ...)  ← maps to SQL column "id INTEGER ..."
#
# When SQLAlchemy sees this class, it knows exactly what SQL to run.
# "Base.metadata.create_all()" is equivalent to all your CREATE TABLE IF NOT EXISTS statements.

from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, func
from sqlalchemy.orm import relationship
from app.core.database import Base


# ─────────────────────────────────────────────
# USER MODEL
# ─────────────────────────────────────────────
class User(Base):
    """
    Maps to the 'users' table.
    
    Old SQL:
        CREATE TABLE users (
            id SERIAL PRIMARY KEY,
            email TEXT UNIQUE NOT NULL,
            name TEXT,
            picture TEXT,
            role TEXT,
            last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            login_count INTEGER DEFAULT 1
        )
    """
    __tablename__ = "users"
    
    # Column(Type, primary_key=True) → "id SERIAL/INTEGER PRIMARY KEY"
    id = Column(Integer, primary_key=True, index=True)
    
    # unique=True → "UNIQUE", nullable=False → "NOT NULL"
    # index=True → creates a database index for fast lookups
    email = Column(String, unique=True, nullable=False, index=True)
    
    name = Column(String, nullable=True)
    picture = Column(String, nullable=True)
    
    # The user's target role (e.g., "Software Engineer")
    role = Column(String, default="Student")
    
    # server_default="now()" → database sets the default (same as CURRENT_TIMESTAMP)
    # We use datetime.utcnow as the Python-side default too
    last_login = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    
    login_count = Column(Integer, default=1)
    
    # --- Relationships ---
    # This tells SQLAlchemy that one User can have many Reports.
    # With this, you can do: user.reports → list of all their reports
    # back_populates="user" → on the Report class, there's a "user" attribute pointing back
    reports = relationship("Report", back_populates="user", cascade="all, delete-orphan")
    saved_jobs = relationship("SavedJob", back_populates="user", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<User id={self.id} email={self.email}>"


# ─────────────────────────────────────────────
# REPORT MODEL
# ─────────────────────────────────────────────
class Report(Base):
    """
    Maps to the 'reports' table.
    Stores AI-generated resume analyses and interview prep results.
    
    Old SQL:
        CREATE TABLE reports (
            id SERIAL PRIMARY KEY,
            user_email TEXT,
            role TEXT,
            content TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """
    __tablename__ = "reports"
    
    id = Column(Integer, primary_key=True, index=True)
    
    # ForeignKey links this column to users.email
    # This enforces referential integrity: you can't have a report
    # for an email that doesn't exist in users table.
    user_email = Column(String, ForeignKey("users.email"), nullable=False, index=True)
    
    # The job role this report is for (e.g., "Data Scientist")
    role = Column(String)
    
    # The full HTML content generated by AI — can be very large
    content = Column(Text)
    
    # func.now() → database-level default timestamp
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    
    # Back-reference to the User who owns this report
    user = relationship("User", back_populates="reports")
    
    def __repr__(self):
        return f"<Report id={self.id} user={self.user_email} role={self.role}>"


# ─────────────────────────────────────────────
# SAVED JOB MODEL
# ─────────────────────────────────────────────
class SavedJob(Base):
    """
    Maps to the 'saved_jobs' table.
    When a user bookmarks a job from the search results.
    
    Old SQL:
        CREATE TABLE saved_jobs (
            id SERIAL PRIMARY KEY,
            user_email TEXT,
            title TEXT, company TEXT, location TEXT, url TEXT,
            created_at TEXT
        )
    """
    __tablename__ = "saved_jobs"
    
    id = Column(Integer, primary_key=True, index=True)
    user_email = Column(String, ForeignKey("users.email"), nullable=False, index=True)
    
    title = Column(String)
    company = Column(String)
    location = Column(String)
    url = Column(String)
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    
    user = relationship("User", back_populates="saved_jobs")
    
    def __repr__(self):
        return f"<SavedJob id={self.id} title={self.title} user={self.user_email}>"


# ─────────────────────────────────────────────
# JOB CACHE MODEL
# ─────────────────────────────────────────────
class JobCache(Base):
    """
    Maps to the 'job_cache' table.
    Caches Adzuna API results to avoid hitting rate limits.
    
    Old SQL:
        CREATE TABLE job_cache (
            search_key TEXT PRIMARY KEY,
            json_data TEXT,
            updated_at TEXT
        )
    """
    __tablename__ = "job_cache"
    
    # search_key is like "software engineer_bangalore"
    # We use it as the primary key since it's unique per search
    search_key = Column(String, primary_key=True, index=True)
    
    # JSON string of the API response
    json_data = Column(Text)
    
    # When this cache entry was created (for cache invalidation)
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    
    def __repr__(self):
        return f"<JobCache key={self.search_key}>"